# Generated by Django 5.2.14 on 2026-06-19 19:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coureses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
