# Generated by Django 5.2.14 on 2026-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coureses', '0002_alter_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
