# Generated by Django 5.2.14 on 2026-06-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coureses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='coureses.module'),
        ),
    ]
