# Generated by Django 5.2.14 on 2026-06-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coureses', '0003_question_order_topic_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
    ]
