# Generated by Django 5.2.14 on 2026-06-22 14:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coureses', '0004_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
