# Generated by Django 5.2.14 on 2026-06-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coureses', '0005_alter_answer_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
    ]
