# Generated by Django 5.2.14 on 2026-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='e_learn/')),
                ('url', models.CharField(max_length=50)),
                ('order', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
