# Generated by Django 5.2.14 on 2026-06-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='e_learn/')),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
