# Generated by Django 5.2.14 on 2026-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learn', '0002_mode_delete_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='url',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
