# Generated by Django 5.2.14 on 2026-06-29 22:56

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coureses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='coureses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', django_ckeditor_5.fields.CKEditor5Field()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizTasks', to='quizes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_correct', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizAnswers', to='quizes.quiz_task')),
            ],
        ),
    ]
