# Generated by Django 5.2.14 on 2026-06-20 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coureses', '0002_alter_question_content'),
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='coureses.course'),
        ),
        migrations.AlterField(
            model_name='quiz_answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizAnswers', to='quizes.quiz_task'),
        ),
        migrations.AlterField(
            model_name='quiz_task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizTasks', to='quizes.quiz'),
        ),
    ]
