# Generated by Django 5.2.14 on 2026-06-26 11:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_answer',
            name='option',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='quiz_task',
            name='context',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
