# Generated by Django 5.2.14 on 2026-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_course_alter_quiz_answer_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
